services:
  transactions-db:
    build:
      context: ./docker/postgres-db
    environment:
      - POSTGRES_USER=${SOURCE_DB_USER}
      - POSTGRES_PASSWORD=${SOURCE_DB_PASSWORD}
      - POSTGRES_DB=${SOURCE_DB}
    volumes:
      - ${PWD}/db-data:/var/lib/postgresql/data
      - ./db-scripts/initialize_db_ddl.sql:/docker-entrypoint-initdb.d/initialize_db_ddl.sql:ro
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "wal_level=logical", "-c", "hot_standby=on"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${SOURCE_DB_USER}:${SOURCE_DB_PASSWORD}@transactions-db:5432/${SOURCE_DB}
      - SOURCE_DB_HOST=transactions-db
      - DEST_DB_HOST=transactions-db
    volumes:
      - ./logs:/app/logs
      - ./output:/app/output
    entrypoint: ["/entrypoint.sh"]
    stdin_open: true
    tty: true

volumes:
  postgres_data:
